queue_rules:
  - name: default
    queue_conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=status-check
pull_request_rules:
  - name: merge PRs labeled ready-to-merge
    conditions:
      - status-success=status-check
      - label=ready-to-merge
    actions:
      merge:
        method: squash
      queue:
        name: default
  - name: delete head branch on merged pull requests
    conditions:
      - merged
      - -head~=^(main|dev)$
      - -author~=^dependabot(|-preview)\[bot\]$
    actions:
      label:
        remove:
          - ready-to-merge
      delete_head_branch:
