name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22] # Define a matrix of Node.js versions to test.There would be 3 jobs for 12.x, 14.x, 16.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2 # Step 1: Check out the source code from the repository.

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.2.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm" # Step 2: Use npm caching for faster dependency installs.

      - name: Install Node.js dependencies
        run: npm ci # Step 3: Perform a clean install of Node.js dependencies.

      - name: Run build
        run: npm run build # Step 4: Run tests using the specified Node.js version.

      - name: Run Tests
        run: npm run test:ci # Step 4: Run tests using the specified Node.js version.
