name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22] # Define a matrix of Node.js versions to test.There would be 3 jobs for 12.x, 14.x, 16.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0 # Step 1: Check out the source code from the repository.

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Run Tests
        run: npm run test:ci

      - name: Run Lint
        run: npm run lint

  status-check:
    if: always()
    name: Finish Test
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
